### ISSUE TITLE
FX files for OBS projects

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#296]
https://github.com/ESMValGroup/ESMValCore/issues/294 and #295 describe a somewhat more general problem - how to find and use fx files from OBS projects when applying various masking preprocessors. The cut-throat approach in #295 needs to be generalized in a more flexible approach and, if the fx files from OBS projects obey the same file naming rules as the OBS files themselves it shouldn't be much of a problem but we need to set these right in `_recipe.py`.

I will do this now but I need to know if the naming rule differs from OBS project to OBS project what these files are called :beer:

**Comment by mattiarighi** [comment]
The `fx` files that we currently have in our `OBS` pool are named like this:
```
./Tier3/NSIDC-0116-sh/OBS_NSIDC-0116-sh_reanaly_4.1_fx_areacello_.nc
./Tier3/NSIDC-0116-nh/OBS_NSIDC-0116-nh_reanaly_4.1_fx_areacello_.nc
./Tier3/ERA-Interim/OBS_ERA-Interim_reanaly_1_fx_sftlf_.nc
```
where the extra `_` has been added due to [this problem](https://github.com/ESMValGroup/ESMValCore/pull/170#issuecomment-531160887).

**Comment by valeriupredoi** [comment]
aha! I was just about to post the same links and ask - will this be the norm for all (expected) others?

**Comment by valeriupredoi** [comment]
also, for various preprocessing masks we need : `['sftlf', 'sftof', 'sftgif']` - are we expecting these to be produced all?

**Comment by mattiarighi** [comment]
I would prefer the version without `_` at the end (see also #250).
Actually #210 should fix this.

**Comment by mattiarighi** [comment]
> also, for various preprocessing masks we need : ['sftlf', 'sftof', 'sftgif'] - are we expecting these to be produced all?

No, the large majority of the obs data do not have them.

**Comment by valeriupredoi** [comment]
yes, I tested using #297 and it works fine for me, also noticed that the files stored in `esmeval` on Jasmin are ye olde as the Middle Ages (ie February) -> @bjoernbroetz maybe a re-sync of the files off DKRZ would be a good idea :beer:

**Comment by bascrezee** [comment]
I also tested using https://github.com/ESMValGroup/ESMValCore/pull/297, but it does NOT work for me. 
```
datasets:
  - {dataset: CDS-SATELLITE-SOIL-MOISTURE, type: sat, project: OBS, mip: Lmon, version: COMBINED-TCDR-v201812.0.0, tier: 3, start_year: 2017,  end_year: 2018}

preprocessors:
  pp_test_glacier_mask:
    mask_landsea:
      mask_out: sea
```


```
2019-10-08 07:23:40,297 UTC [8801] ERROR   Program terminated abnormally, see stack trace below for more information
Traceback (most recent call last):
  File "ESMValCore/esmvalcore/_main.py", line 228, in run
    conf = main(args)
  File "ESMValCore/esmvalcore/_main.py", line 156, in main
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "ESMValCore/esmvalcore/_main.py", line 202, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "ESMValCore/esmvalcore/_recipe.py", line 72, in read_recipe_file
    recipe_file=filename)
  File "ESMValCore/esmvalcore/_recipe.py", line 878, in __init__
    self.tasks = self.initialize_tasks() if initialize_tasks else None
  File "ESMValCore/esmvalcore/_recipe.py", line 1225, in initialize_tasks
    task_name=task_name,
  File "ESMValCore/esmvalcore/_recipe.py", line 849, in _get_preprocessor_task
    name=task_name,
  File "ESMValCore/esmvalcore/_recipe.py", line 717, in _get_single_preprocessor_task
    config_user=config_user,
  File "ESMValCore/esmvalcore/_recipe.py", line 667, in _get_preprocessor_products
    config_user=config_user)
  File "ESMValCore/esmvalcore/_recipe.py", line 434, in _update_fx_settings
    'sftlf': _get_correct_fx_file(variable, 'sftlf', config_user),
  File "ESMValCore/esmvalcore/_recipe.py", line 406, in _get_correct_fx_file
    drs=config_user['drs'])[0]
IndexError: list index out of range
2019-10-08 07:23:40,300 UTC [8801] INFO    If you suspect this is a bug or need help, please open an issue on https://github.com/ESMValGroup/ESMValTool/issues and attach the run/recipe_*.yml and run/main_log_debug.txt files from the output directory.
```

**Comment by valeriupredoi** [comment]
That's because the obs files you have do not end in _.nc, also pls pull the
latest branch, I fixed the empty list issue

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom

**Comment by bascrezee** [comment]
> That's because the obs files you have do not end in _.nc
I don't understand this, but it is maybe not relevant for the issue?

> also pls pull the latest branch, I fixed the empty list issue
Yes, I pulled that, I think it is not fixed yet. If I do the change in l406 as I write above , it works for my case.

**Comment by mattiarighi** [comment]
> I don't understand what you mean here..

See the discussion in #250.
If you are using the `default` drs for `OBS`, the filename structure is expected to be:
```
[project]_[dataset]_[type]_[version]_[mip]_[short_name]_*.nc
```
which could be a problem for `fx` files.

**Comment by mattiarighi** [comment]
We should try to merge #210 asap to fix this trouble with `_`.
I'm testing that branch now.

**Comment by valeriupredoi** [comment]
Crap! you are right, the 0th index is still there, my bad, that needs out.
Also, the underscore as the last character before the .nc extension is a
kludge introduced by #170 -> @mattiarighi can tell you all about it

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom

**Comment by bascrezee** [comment]
Ok, I kind of understand the underscore issue. Thanks for the info. I will just wait a bit for this stuff to be fixed before I continue working on https://github.com/ESMValGroup/ESMValCore/pull/246.

**Comment by mattiarighi** [comment]
#210 and #297 should have addressed this.

@bascrezee if you have further remarks while working on #246 please open a dedicated issue.

**Comment by bjoernbroetz** [comment]
> ... also noticed that the files stored in esmeval on Jasmin are ye olde as the Middle Ages (ie February) -> @bjoernbroetz maybe a re-sync of the files off DKRZ would be a good idea beer

Thanks @valeriupredoi, the sync is running right now.
