### ISSUE TITLE
Problem preprocessing ACCESS1-3 and IPSL-CM5A-LR piControl data

### ISSUE THREAD

**Issue by ValerioLembo** [ESMValGroup/ESMValCore#58]
This issue is related to porting the diagnostic tool for thermodynamics into version 2.0 of ESMValTool. Progress is tracked in [this](https://github.com/ESMValGroup/ESMValTool-private/tree/version2_Thermodyn_diagtool) branch.

EDIT: the recipe has been ported, but there are remaining issues with preprocessing piControl data for experiments ACCESS1-3 and IPSL-CM5A-LR.

**Comment by valeriupredoi** [comment]
@ValerioLembo does this need revisiting or has been solved for you in the meantime? :beer:

**Comment by ValerioLembo** [comment]
@valeriupredoi I made a quick test and it seems to me that the problem with ACCESS1-3 is solved, whereas the one with IPSL-CM5A-LR still persists...

**Comment by zklaus** [comment]
This issue deals with many problems. I am not sure if a dataset error is still one of them (one problem might be that 'months' is not an acceptable unit in the CF sense). @valeriupredoi could you please figure out the situation, probably with @ValerioLembo and file one or two issues using our dataset problem template if this is still relevant?

**Comment by valeriupredoi** [comment]
Yep, will be on it today :beer:

**Comment by valeriupredoi** [comment]
@ValerioLembo - I ran this toy recipe:
```
datasets:
  - {dataset: IPSL-CM5A-LR, project: CMIP5, exp: piControl, ensemble: r1i1p1, start_year: 1990, end_year: 2000}

diagnostics:
  Thermodyn_Diag:
    description: Thermodynamics diagnostics
    variables:
      ta:
        mip: day
      sftlf:
        mip: fx
      ua:
        mip: day
      va:
        mip: day
      wap:
        mip: day
    scripts:
      Thermodyn_Diag:
        script: thermodyn_diagtool/thermodyn_diagnostics.py
        wat: true
        lec: true
        entr: true
        met: 3
        lsm: true
```
and noticed no problem in the preprocessor, there was a problem in the diagnostic but not related to data structures - can you pls tell me which data spec for IPSL-CM5A-LR is still problematic? :beer:

**Comment by ValerioLembo** [comment]
@valeriupredoi The issue is with the monthly mean data, e.g. hfls...

**Comment by valeriupredoi** [comment]
like this? This one went fine too, preprocessor-wise:
```
datasets:
  - {dataset: IPSL-CM5A-LR, project: CMIP5, exp: piControl, ensemble: r1i1p1, start_year: 2370, end_year: 2390}

diagnostics:
  Thermodyn_Diag:
    description: Thermodynamics diagnostics
    variables:
      hfls:
        mip: Amon
      hfss:
        mip: Amon
    scripts:
      Thermodyn_Diag:
        script: thermodyn_diagtool/thermodyn_diagnostics.py
        wat: true
        lec: true
        entr: true
        met: 3
        lsm: true
```

**Comment by valeriupredoi** [comment]
...and this one has no preprocessing issues either - @ValerioLembo can you please post a recipe snippet that is failing for you at preprocessor stage, and aslo add the ful trace please :beer:
```
datasets:
  - {dataset: IPSL-CM5A-LR, project: CMIP5, exp: piControl, ensemble: r1i1p1, start_year: 1995, end_year: 2000}

diagnostics:
  Thermodyn_Diag:
    description: Thermodynamics diagnostics
    variables:
      hfls:
        mip: day
      hfss:
        mip: day
    scripts:
      Thermodyn_Diag:
        script: thermodyn_diagtool/thermodyn_diagnostics.py
        wat: true
        lec: true
        entr: true
        met: 3
        lsm: true
```

**Comment by ValerioLembo** [comment]
Hi there,

the problem with IPSL-CM5A-LR was related to an old version of the hfls dataset I had on my local repository. I changed that and it seems to work fine. 

Unfortunately I cannot test the whole diagnostics, because there are some missing datasets on the DKRZ repository for piControl...

**Comment by valeriupredoi** [comment]
cool, cheers for checking @ValerioLembo - guess it's okay to close this for now and open another one if need be, if another dataset is broken :beer:
